// Code generated by go-swagger; DO NOT EDIT.

// Package restapi TO DO LIST API
//
//  to do list API
//  Schemes:
//    http
//    https
//  Host: 198.1.1.26:8888
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
